openapi: 3.0.0
components:
  schemas:
    Employee:
      title: Employee
      type: object
      description: Employee Info
      properties:
        id:
          type: string
          minLength: 5
          maxLength: 10
        companyId:
          type: number
          example: 999
        role:
          type: string
          example: ENGINEER
          enum:
            - MANAGER
            - ENGINEER
            - ASSISTANT
        name:
          type: string
          example: John Doe
        registdate:
          type: string
          format: date-time
        profile:
          $ref: '#/components/schemas/Profile'
        department:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
              enum:
                - Marketing
                - Human Resouce
                - Development
    Profile:
      title: Profile
      type: object
      properties:
        age:
          type: number
          minimum: 18
          maximum: 50
        birthdate:
          type: string
          format: date
        sex:
          type: string
          enum:
            - MALE
            - FEMALE
            - ELSE
        hobby:
          type: array
          items: 
            type: string
            example: watching movies